services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      timeout: 3s
      retries: 5
      interval: 600s
      start_period: 20s
      start_interval: 2s
    networks:
      - internal

  app:
    build:
      context: ..
      dockerfile: app/Dockerfile
    image: money-pulso-app:local
    container_name: money-pulso-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - WS_PERIODIC_RECYCLE_SEC=${WS_PERIODIC_RECYCLE_SEC:-14400}
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
      uv run alembic upgrade head
      &
      uv run uvicorn app.__main__:app
      --host 0.0.0.0
      --port 8000
      --log-level info
      --proxy-headers
      --forwarded-allow-ips=*
      "
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    networks:
      internal:
      apps_network:
        ipv4_address: 172.20.0.8   # опционально; можно убрать строку — тогда IP динамический
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=apps_network"
      - "traefik.http.routers.money-pulso.rule=Host(`screener.dmitryrod.ru`)"
      - "traefik.http.routers.money-pulso.entrypoints=websecure"
      - "traefik.http.routers.money-pulso.tls=true"
      - "traefik.http.routers.money-pulso.tls.certresolver=letsencrypt"
      - "traefik.http.services.money-pulso.loadbalancer.server.port=8000"

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
  apps_network:
    external: true