# Включить автоисправление
fix = true

# Длина строка
line-length = 100

# Исключаем тесты на проверки
exclude = ["tests", "migrations", "*.html"]

#Выбрать правила - не слишком строгие, но полезные
lint.select = [
    "E",                # стандартные ошибки синтаксиса
    "F",                # pyflakes (неиспользуемые импорты и г.д.)
    "I",                # isort (сортировка импортов)
    "UP",               # улучшения синтаксиса под новые версии Python
    "B",                # обнаружение потенциальных багов (flake8-bugbear)
    "PERF",             # performance - подсказки по улучшению производительности
    "FIX002",           # проверка TODO
    "PLE",              # pylint errors
    "PLW",              # pylint warnings
    "F822",             # неопределенные имена в __all__
    # "D",              # правила pydocstyle
]
# Игнорировать некоторые слишком строгие правила
lint.ignore = [
    "E501", # длина строки
    "D104", # документация для публичного пакета
    "D100", # документация для публичного модуля
]